### ISSUE TITLE
PUT and DELETE verbs are ignored

### ISSUE THREAD

**Issue by crixo** [MacLeanElectrical/servicestack-introspec#13]
I noticed the verbs PUT and DELETE provided through the Route attribute are ignored within ApiDocumentation.
ApiDocumentation -> Resources ->Actions does not list those verbs unless the service that handle the DTO (decorated with the Route attribute) contains an explicit method Put and/or Delete: using the Any method the 2 verbs are ignored.

```
public class MyDtoService : Service
{
    //public object Get(MyDto request) => new MyDtoResponse();
    //public object Delete(MyDto request) => new MyDtoResponse();
    //public object Post(MyDto request) => new MyDtoResponse();
    //public object Put(MyDto request) => new MyDtoResponse();
    public object Any(MyDto request) => new MyDtoResponse();
}

[Route("/items/{Name}/", "PUT")]
//[Route("/items", "POST")]
public class MyDto : IReturn<MyDtoResponse>
{
    ....
}
```

**Comment by wwwlicious** [comment]
Thanks for submitting this, we will investigate.

**Comment by donaldgray** [comment]
The current behaviour is that when an `Any()` method is present within a Service the value of the `[ReplacementVerbs](https://github.com/MacLeanElectrical/servicestack-introspec/blob/master/docs/settings.md#settings)` global setting is used to define which verbs are documented in the APIDocumentation output, this is defaulted to GET and POST. 

This behaviour is incorrect in this instance as PUT would be available on "/items/{Name}/" whereas all other verbs would be available on the automatic routes setup by ServiceStack.

I'll make an update to take verbs defined within RouteAttribute into account when generating docs.

**Comment by donaldgray** [comment]
Issue should now be resolved - updated logic to take verbs from `RouteAttribute` into account.

The `ReplacementVerbs` setting will still be taken into account but will be Union'd with any verbs found in `RouteAttribute`. So in the following example:

```cs 
DocumenterSettings.ReplacementVerbs = new[] { "GET", "POST" };

public class MyDtoService : Service
{
    public object Delete(MyDto request) => new MyDtoResponse();
    public object Any(MyDto request) => new MyDtoResponse();
}

[Route("/items/{Name}/", "PUT")]
public class MyDto : IReturn<MyDtoResponse>
{
    ....
}
```

The output would be for the verbs:

- DELETE (from service method `Delete(MyDto request)`)
- PUT (from `RouteAttribute`)
- GET (from `DocumenterSettings.ReplacementVerbs` setting)
- POST (from `DocumenterSettings.ReplacementVerbs` setting)
