### ISSUE TITLE
swagger 2.0

### ISSUE THREAD

**Issue by crixo** [MacLeanElectrical/servicestack-introspec#2]
I noticed you already implemented an extension to support RAML.
Are you planning to support swagger 2.0 as well?

**Comment by donaldgray** [comment]
Hi @crixo, thanks for having a look at the plugin.

For the moment Swagger 2.0 support isn't something that we have plans to implement.

The idea behind the models created by the Introspec plugin is that they can be used as the base to generate different API documentation standards so it should be possible to generate Swagger 2.0. 

If this is something that you need and are looking into then we're happy to look at any changes to Introspec to support this (or we accept PR's if you prefer!).
